IF !DEF(IMAGES_INC)
DEF IMAGES_INC = 1

    EXPORT mushysplash_map_data
    EXPORT mushysplash_map_data_end

    EXPORT mushysplash_tile_data
    EXPORT mushysplash_tile_data_end


    EXPORT mushystory1_map_data
    EXPORT mushystory1_map_data_end

    EXPORT mushystory1_tile_data
    EXPORT mushystory1_tile_data_end


    EXPORT mushystory2_map_data
    EXPORT mushystory2_map_data_end

    EXPORT mushystory2_tile_data
    EXPORT mushystory2_tile_data_end


    EXPORT mushystory3_map_data
    EXPORT mushystory3_map_data_end

    EXPORT mushystory3_tile_data
    EXPORT mushystory3_tile_data_end

ENDC